name: BlueNova LaunchPad
description: Github Action used to deploy to the BlueNova cloud environment.
author: "@bluenovaio"
inputs:
  name:
    description: "The name of the service (must be unique) to be deployed."
    required: true
  port:
    description: "The port that the application will run on in the container."
    required: false
    default: "8080"
  api_key:
    description: "The API Key provided by BlueNova, used to associate all requests."
    required: true
  service_account_key:
    description: "The Service Account JSON Key used to push images to the BlueNova Container Registry."
    required: true
  github_token:
    description: "Github Token, pass in the secrets.GITHUB_TOKEN."
    required: true
  directory:
    description: "Directory where the DockerFile is located."
    required: false
    default: "."
outputs: {}
runs:
  using: node12
  main: dist/index.js
