name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  testAction:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: runAction
        name: Run Action Code
        uses: ./
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          name: action-launchpad-example
          api_key: ${{ secrets.BLUENOVA_API_KEY }}
