name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  testAction:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: runAction
        name: Run Action Code
        uses: ./
        env:
          MESSAGE: 'Hello via ENV Vars'
        with:
          directory: ./examples/nodejs-simple
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          name: gha-example
          api_key: ${{ secrets.BLUENOVA_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
