name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  testAction:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: runAction
        name: Run Action Code
        uses: ./
        with:
          directory: ./examples/nodejs-simple
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          name: ghaexample
          port: 3000
          dockerfile: ./examples/nodejs-simple/DevDockerfile
          api_key: ${{ secrets.BLUENOVA_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_args: BUILD_VAR=foo,BUILD_VAR2=bar
          env_vars: MESSAGE="Hello via ENV Vars"
      - name: Test Outputs
        run: echo "${{ steps.runAction.outputs.url }}"
